// 本模块 vendored 自 termux-app @ 3df69d1（Apache License 2.0，详见 src 内文件头与 LICENSES/）
// build.gradle 已按 AndroLinux 工程需求重写（去除 termux 发布配置）
plugins { id 'com.android.library' }

android {
    namespace 'com.termux.view'
    compileSdk 36

    defaultConfig {
        minSdk 28
        targetSdk 28
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint { abortOnError false }

    dependencies {
        implementation 'androidx.annotation:annotation:1.9.0'
        api project(':terminal-emulator')
    }
}
